framework/src/Litepie/Menu/routes/web.php
<?php

// Admin  routes  for menu.
Route::prefix('{guard}/menu')->group(function () {
    
    Route::post('menu/{id}/tree', 'MenuResourceController@tree');
    Route::get('menu/{id}/test', 'MenuResourceController@test');
    Route::get('menu/{id}/nested', 'MenuResourceController@nested');

    Route::resource('menu', 'MenuResourceController');
    Route::resource('submenu', 'SubMenuResourceController');
});

if (Trans::isMultilingual()) {
    Route::group(
        [
            'prefix' => '{trans}',
            'where'  => ['trans' => Trans::keys('|')],
        ],
        function () {
            Route::group(['prefix' => '{guard}/menu'], function () {
                Route::post('menu/{id}/tree', 'MenuResourceController@tree');
                Route::get('menu/{id}/test', 'MenuResourceController@test');
                Route::get('menu/{id}/nested', 'MenuResourceController@nested');

                Route::resource('menu', 'MenuResourceController');
                Route::resource('submenu', 'SubMenuResourceController');
            });
        }
    );
}

framework/src/Litepie/Menu/Models/Menu.php
<?php

namespace Litepie\Menu\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Litepie\Database\Model;
use Litepie\Database\Traits\Sluggable;
use Litepie\Hashids\Traits\Hashids;
use Litepie\Node\Traits\SimpleNode;
use Litepie\Trans\Traits\Translatable;

class Menu extends Model
{
    use Hashids, Sluggable, Translatable, SoftDeletes, SimpleNode;

    /**
     * Configuartion for the model.
     *
     * @var array
     */
    protected $config = 'menu.menu';

    public function getHasRoleAttribute($value)
    {
        if (empty($this->role)) {
            return true;
        }

        if (is_array($this->role) && user()->isOne($this->role)) {
            return true;
        }

        return false;
    }
}

framework/src/Litepie/Menu/resources/views/admin/menu/admin.blade.php
@foreach ($menus as $menu)
    @if($menu->has_role)
    @if ($menu->hasChildren())
    <li class="treeview {{ $menu->active ?? '' }}">
        <a href="{{trans_url($menu->url)}}" >
            <i class="{{{ $menu->icon ?? 'fa fa-angle-double-right' }}}"></i> <span>{{$menu->name}}</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        @include('menu::menu.sub.admin', array('menus' => $menu->getChildren()))
    </li>
    @else
    <li  {{ $menu->active ?? '' }}>
        <a href="{{trans_url($menu->url)}}">
            <i class="{{{ $menu->icon ?? 'fa fa-angle-double-right' }}}"></i>
            <span>{{$menu->name}}</span>
        </a>
    </li>
    @endif
    @endif
@endforeach

framework/src/Litepie/Menu/resources/views/admin/menu/nestable.blade.php
<div class="dd nestable-menu" id="nestable">
    <ol class="dd-list">
    @foreach ($menus as $menu)
        @if ($children = $menu->getChildren())
        <li class="dd-item dd3-item" data-id="{!!$menu->getRouteKey()!!}">
            <div class="dd-handle dd3-handle"><i class="las la-arrows-alt"></i></div>
            <div class="dd3-content">
                <a href="#" class="app-submenu-edit" data-action="LOAD" data-load-to='#menu-entry' data_val="{!!$menu->getRouteKey()!!}" data-href='{{guard_url('menu/submenu')}}/{!!$menu->getRouteKey()!!}'>
                    <span><i class="{!! !empty($menu->icon) ?  $menu->icon : '' !!}"></i> {!!$menu->name!!}</span>
                </a>
            </div>
            <ol class="dd-list">
            @include( 'menu::admin.menu.sub.nestable', array('menus' => $children))
               
            </ol>
        </li>
        @else
        <li class="dd-item dd3-item" data-id="{!!$menu->getRouteKey()!!}">
            <div class="dd-handle dd3-handle"><i class="las la-arrows-alt"></i></div>
            <div class="dd3-content">
                <a href="#" class="app-submenu-edit" data-action="LOAD" data-load-to='#menu-entry' data_val="{!!$menu->getRouteKey()!!}" data-href='{{guard_url('menu/submenu')}}/{!!$menu->getRouteKey()!!}'>
                    <span><i class="{!! !empty($menu->icon) ?  $menu->icon : '' !!}"></i> {!!$menu->name!!}</span>
                </a>
            </div>
        </li>
        @endif
        @endforeach
    </ol>
</div>
<script>
$(document).ready(function() {
    $(".app-submenu-edit").click(function(e) {
            e.preventDefault();   
            var id = $(this).attr('data_val');
        $("#app-content").load('{{guard_url('menu/submenu')}}'+'/'+id+'/edit');
    });
});
</script>